#!/usr/bin/env python2

import os, sys
import pygame
from pygame.locals import *


class Car:
	def __init__(self, image, height, speed):
		self.image = image
		self.speed = speed
		self.pos = image.get_rect().move(0,height)
	def move(self):
		self.pos = self.pos.move(0, self.speed)
		if self.pos.right > 660:
			self.pos.left = 0

class Pedestrian:
	def __init__(self, height, speed):
		self.speed = speed
		self.pos = image.get_circle().move(0,height)
	def move(self):
		self.pos = self.pos.move(0, self.speed)
		if self.pos.right > 600:
			self.pos.left = 0

if len(sys.argv) < 2:
	print "useage: ./VIS <filename>"

filename = sys.argv[1]

f = open(filename, 'r')

pygame.init()
pygame.font.init()

screen = pygame.display.set_mode((700, 480))
pygame.display.set_caption('Crosswalk Simulator')
pygame.mouse.set_visible(0)

car_right_pic = pygame.image.load('right_car.png').convert()
car_left_pic = pygame.image.load('left_car.png').convert()

background = pygame.Surface(screen.get_size())
background = background.convert()
background.fill((250, 250, 250))

cars = []
for line in f.readlines():
	c = Car(car_left_pic, 60, 1)
	cars.append(c)

#screen.blit(background, (0,0))
pygame.display.flip()

clock = pygame.time.Clock()

cars = []
o = Car(car_left_pic, 40, 1)

while 1:
	for event in pygame.event.get():
		if event.type in (QUIT, KEYDOWN):
			sys.exit()
	o.move()
	screen.blit(o.image, o.pos)
	pygame.display.update()
	pygame.time.delay(100)
